### ISSUE TITLE
How to export texture?

### ISSUE THREAD

**Issue by haianh97** [REDxEYE/ProjectDecima#4]
I can export core file but how to export png file and preview it?

**Comment by ShadelessFox** [comment]
As #3 now you can preview textures by opening desired 'Texture' entry inside core file and export them by right-clicking on its preview

**Comment by haianh97** [comment]
it beats me!

**Comment by ShadelessFox** [comment]
Can you explain?

**Comment by haianh97** [comment]
![image](https://user-images.githubusercontent.com/30430562/89853048-7ca7e780-dbba-11ea-92c3-a4603a5b356c.png)
where export texture and preview it?

**Comment by ShadelessFox** [comment]
If this is Horizon, then its texture format is not supported yet. Exporting and previewing should work "fine" for Death Stranding at this moment.

**Comment by haianh97** [comment]
Thank you.
