### ISSUE TITLE
Game reflection data

### ISSUE THREAD

**Issue by Nukem9** [REDxEYE/ProjectDecima#7]
Hi,

I'm not sure if you guys are aware, but the HZD executable embeds reflection data (aka GGRTTI) that's used for Core file reading. I reverse engineered the structures and dumped it all* to a file: https://gist.github.com/Nukem9/391bff651df883a785f2af1e1b07e5b7. I made it to be human readable and it's not in any specific language or layout. Hopefully this is better than figuring out the binary formats by hand.

I don't know if Death Stranding has the same data - I don't own the game, so I can't check for myself.
<br /> 
\* Technically not _all_ RTTI since certain types aren't referenced or are debug only. The game never registers them in the global type map.

**Comment by REDxEYE** [comment]
I can provide you Death Stranding executable if you want

**Comment by REDxEYE** [comment]
Some structures have quite big size, but does not contain any members, is this normal?

**Comment by Nukem9** [comment]
> I can provide you Death Stranding executable if you want

I need to own the game myself because the fields have to be dumped at runtime. There's no DS crack available, so I'm stuck with HZD for now.

> Some structures have quite big size, but does not contain any members, is this normal?

Yes, the class size has nothing to do with the data in the Core file. GGRTTI defines properties and class members that are serialized in the binary format, but not in memory. They are also sorted by offset. Here's an example:

```cpp
// Binary type = 0x69F066DDC22139DB
// sizeof() = 0x8
class RTTIObject
{
};

class RTTIRefObject : RTTIObject
{
	GGUUID ObjectUUID;// 0xC
};
class CoreObject : RTTIRefObject {}
class BaseResource : CoreObject {}

// Binary type = 0x83E784D26B042AC8
// sizeof() = 0x28
class Resource : BaseResource
{
	String Name;// 0x20
};
```

Reading a RTTIObject entry:
```cpp
--- Core entry header ---
uint64_t BinaryType; // = 0x69F066DDC22139DB
uint32_t ChunkSize;  // = 0
--- RTTIObject ---
```

Reading a Resource entry:
```cpp
--- Core entry header ---
uint64_t BinaryType; // = 0x83E784D26B042AC8
uint32_t ChunkSize;  // = sizeof(GGUUID) + sizeof(String)
--- Resource ---
GGUUID ObjectUUID;   // uint8_t[16] (inherited from RTTIRefObject)
String Name;         // uint32_t + uint32_t + char[X]
```
---
 If you want a reference I implemented my own types [in C# here](https://github.com/Nukem9/HZDCoreEditor/tree/master/HZDCoreEditor/Decima/Types). It's still experimental/buggy/a work in progress though.

**Comment by REDxEYE** [comment]
> I need to own the game myself because the fields have to be dumped at runtime. There's no DS crack available, so I'm stuck with HZD for now.

Maybe steam library share would help?

**Comment by Nukem9** [comment]
> > I need to own the game myself because the fields have to be dumped at runtime. There's no DS crack available, so I'm stuck with HZD for now.
> 
> Maybe steam library share would help?

I guess that can work. Here's my profile if you want to add me: https://steamcommunity.com/id/Nukem9/
