### ISSUE TITLE
x64 release crashing when opening archive

### ISSUE THREAD

**Issue by 3my** [REDxEYE/ProjectDecima#9]
I used DecimaExplorer to extract a bunch of the sound .core files and tried to open them up using ProjectDecima (latest release [0.1.7]) but it seems to always crash upon choosing "Select Folder".

**Comment by ShadelessFox** [comment]
What exactly folder caused a crash? It must be the folder containing .bin files, not the game folder itself.
For example, when working with Death Stranding you must select `GAME_DIR/data`
